version: '3.8'
services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  nginx:
    image: nginx:latest
    container_name: ng01
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/yamdb_final/static
    depends_on:
      - web
  web:
    build: .
    restart: always
    command: gunicorn api_yamdb.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/yamdb_final/static
    expose:
      - 8000
    depends_on:
      - db
    env_file:
      - ./.env
volumes:
  postgres_data: